spring.application.name=whodo-paymentorder-service
server.port=8444
################# Certificate Configuration #################
server.ssl.enabled=true
server.ssl.key-store=classpath:whodo_paymentorder_serv_cert.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=whodo_paymentorder_serv_cert

#################### MercadoPago Configuration #################
mercado.pago.access.token=APP_USR-3506570047038265-102919-ad5e86e17f2be29564b1879aa271d7fe-2955353326

#################### MongoDB Configuration #################
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=whodo-prod
spring.data.mongodb.uri=mongodb+srv://gonzajd777:Fggk6BsEg2wgEVpo@whodo-cluster-ar.ndbfjmf.mongodb.net/

#################### Logging Configuration #################

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor=ERROR
logging.level.com.fasterxml.jackson.databind=ERROR
logging.level.org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor=ERROR
logging.level.org.springframework=ERROR
logging.level.org.springframework.web=ERROR
logging.level.com.fasterxml.jackson=ERROR
logging.level.org.springframework.web.servlet.DispatcherServlet=ERROR
logging.level.org.apache.catalina=ERROR
logging.level.com.whodo.workorder_service=DEBUG

logging.level.org.mongodb.driver=WARN
logging.level.com.mongodb=WARN
logging.level.com.example.whodo_paymentorder_service=INFO

###logging.file.name=logs/paymentorder.log
logging.pattern.console="%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
logging.pattern.file="%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
spring.output.ansi.enabled=ALWAYS


#################### Serializacion #################
spring.jackson.property-naming-strategy=SNAKE_CASE

#################### Metrics #################
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
### http://localhost:8444/actuator/prometheus

#################### RestClient Configration #################
rest.client.config.pool.maxConnectionsPool=200
rest.client.config.pool.maxConnectionsPerRoute=50

 ####// MercadoPago RestClient Configuration
rest.client.url.MercadoPago=https://api.mercadopago.com
rest.client.config.MercadoPago.connectionTimeout=5000
rest.client.config.MercadoPago.readTimeout=5000

####// WorkOrderService RestClient Configuration
rest.client.url.WorkOrderService=https://localhost:8443/api/work-orders
rest.client.config.WorkOrderService.connectionTimeout=5000
rest.client.config.WorkOrderService.readTimeout=5000

